Repository Deseteral/lebkuchen-fm, pull requests merged in 2021-10, with the labels that each got.

#96 added conditions to search query (only embeddable videos, no safe sea…
  packages/fm-player/src/services/youtube-player-service.ts
  packages/service/src/domain/commands/processors/add-command.ts
  packages/service/src/domain/commands/processors/queue-command.ts
  packages/service/src/domain/commands/processors/random-command.ts
  packages/service/src/youtube/youtube-data-client.ts
Labels: hacktoberfest-2020

#118 Upgrade dependencies
  .github/workflows/build.yml
  package-lock.json
  package.json
  packages/admin-panel/package-lock.json
  packages/admin-panel/package.json
  packages/admin-panel/src/admin-panel.html
  packages/devops/package-lock.json
  packages/devops/package.json
  packages/fm-player/package-lock.json
  packages/fm-player/package.json
  packages/fm-player/src/fm-player.html
  packages/service/package-lock.json
  packages/service/package.json
  packages/service/src/api/slack/model/slack-response-dto.ts
  packages/service/src/api/text/model/text-command-response-dto.ts
  packages/service/src/domain/commands/processors/add-command.ts
  packages/service/src/domain/commands/processors/skip-command.ts
  packages/service/src/domain/commands/processors/speed-command.ts
Labels: maintenance

#117 XSounds in file storage
  README.md
  packages/devops/.npmrc
  packages/devops/package-lock.json
  packages/devops/package.json
  packages/devops/scripts/backup-xsounds.js
  packages/devops/scripts/helpers.js
  packages/fm-player/src/components/App.tsx
  packages/fm-player/src/components/XSoundUploadForm.tsx
  packages/service/package-lock.json
  packages/service/package.json
  packages/service/src/api/error-response.ts
  packages/service/src/api/songs/songs-controller.ts
  packages/service/src/api/x-sounds/x-sounds-controller.ts
  packages/service/src/domain/commands/processors/add-x-command.ts
  packages/service/src/domain/commands/registry/command-initializer.ts
  packages/service/src/domain/x-sounds/x-sounds-controller.ts
  packages/service/src/domain/x-sounds/x-sounds-service.ts
  packages/service/src/infrastructure/configuration.ts
  packages/service/src/infrastructure/file-storage.ts
  packages/service/src/lib.ts
  packages/service/src/main.ts
Labels: feature, maintenance, service
